# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbzmerge_MainWindow.ui',
# licensing of 'cbzmerge_MainWindow.ui' applies.
#
# Created: Tue Sep 24 18:18:01 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(650, 720))
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.labelAdded = QtWidgets.QLabel(self.centralwidget)
        self.labelAdded.setObjectName("labelAdded")
        self.gridLayout.addWidget(self.labelAdded, 0, 0, 1, 1)
        self.listAdded = QtWidgets.QListWidget(self.centralwidget)
        self.listAdded.setMinimumSize(QtCore.QSize(591, 491))
        self.listAdded.setDragEnabled(True)
        self.listAdded.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listAdded.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listAdded.setObjectName("listAdded")
        self.gridLayout.addWidget(self.listAdded, 1, 0, 1, 4)
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setMinimumSize(QtCore.QSize(141, 61))
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 2, 0, 1, 1)
        self.btnRemove = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemove.setEnabled(False)
        self.btnRemove.setMinimumSize(QtCore.QSize(141, 61))
        self.btnRemove.setObjectName("btnRemove")
        self.gridLayout.addWidget(self.btnRemove, 2, 1, 1, 1)
        self.btnRemoveAll = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemoveAll.setEnabled(False)
        self.btnRemoveAll.setMinimumSize(QtCore.QSize(141, 61))
        self.btnRemoveAll.setObjectName("btnRemoveAll")
        self.gridLayout.addWidget(self.btnRemoveAll, 2, 2, 1, 1)
        self.btnMerge = QtWidgets.QPushButton(self.centralwidget)
        self.btnMerge.setEnabled(False)
        self.btnMerge.setMinimumSize(QtCore.QSize(141, 61))
        self.btnMerge.setObjectName("btnMerge")
        self.gridLayout.addWidget(self.btnMerge, 2, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(591, 41))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 650, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAboutQT = QtWidgets.QAction(MainWindow)
        self.actionAboutQT.setObjectName("actionAboutQT")
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAboutQT)
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.btnAdd, QtCore.SIGNAL("clicked()"), MainWindow.btnAdd_clicked)
        QtCore.QObject.connect(self.btnRemove, QtCore.SIGNAL("clicked()"), MainWindow.btnRemove_clicked)
        QtCore.QObject.connect(self.btnRemoveAll, QtCore.SIGNAL("clicked()"), MainWindow.btnRemoveAll_clicked)
        QtCore.QObject.connect(self.btnMerge, QtCore.SIGNAL("clicked()"), MainWindow.btnMerge_clicked)
        QtCore.QObject.connect(self.listAdded, QtCore.SIGNAL("itemSelectionChanged()"), MainWindow.selectionChanged)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL("triggered()"), MainWindow.showAbout)
        QtCore.QObject.connect(self.actionAboutQT, QtCore.SIGNAL("triggered()"), MainWindow.showAboutQt)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "cbzmerge", None, -1))
        self.labelAdded.setText(QtWidgets.QApplication.translate("MainWindow", "Added files", None, -1))
        self.btnAdd.setText(QtWidgets.QApplication.translate("MainWindow", "Add", None, -1))
        self.btnRemove.setText(QtWidgets.QApplication.translate("MainWindow", "Remove selected", None, -1))
        self.btnRemove.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Del", None, -1))
        self.btnRemoveAll.setText(QtWidgets.QApplication.translate("MainWindow", "Remove all", None, -1))
        self.btnMerge.setText(QtWidgets.QApplication.translate("MainWindow", "Merge", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionAboutQT.setText(QtWidgets.QApplication.translate("MainWindow", "AboutQt", None, -1))

